services:
  rag:
    build: .
    container_name: rag
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # - GOOGLE_API_KEY=
      # - MONGODB_ATLAS_URI=
      # - MONGODB_ATLAS_DB_NAME=talk-to-pdf
      # - MONGODB_ATLAS_COLLECTION_NAME=pdfs
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./uploads:/app/uploads
    depends_on:
      - redis

  worker:
    build: .
    container_name: pdf_worker
    command: ["npm", "run", "dev:worker"]
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis-data:/data

volumes:
  redis-data: